### ISSUE TITLE
code for CIFAR_FS and FC100

### ISSUE THREAD

**Issue by dennix94** [seongmin-kye/MCT_DFMN#2]
Hi, many thanks for the source code. It is very helpful.
Do you plan to release the settings for these smaller datasets as well?
I tried to use it for CIFAR-FS but the backbone output is too small for the length-scaling module.

Thanks a lot.

**Comment by seongmin-kye** [comment]
Thank you for your attention!
As described in paper, we use max-pooling only in even layers for CIFAR-FS and FC100.
And then if you change self.fc1_pt = nn.Linear(16, 1) >> self.fc1_pt = nn.Linear(36, 1), it will be working.

I will post additional codes as soon as they are organized.

**Comment by dennix94** [comment]
Thanks for your prompt reply!  It works well.
