### ISSUE TITLE
model could not convergent

### ISSUE THREAD

**Issue by jjn037** [seongmin-kye/MCT_DFMN#4]
I set input image size to 224, and self.fc1_pt = nn.Linear(144, 1), but the  model could not convergent。Could you give me some advice about the problem

**Comment by seongmin-kye** [comment]
Hmm,,,, I didn't use 224x224 image. But, I think that problem may occurs in dense classification. So, if you use more layer with max-pooling or 2 stride Conv to make compact informative feature map, dense classification could extract image inherent information.

**Comment by jjn037** [comment]
thx, may be I make some mistakes ,trying to make it
