### ISSUE TITLE
Is this a trick to set the training way to 15?

### ISSUE THREAD

**Issue by Dylanbron** [seongmin-kye/MCT_DFMN#7]
I notice that you set the n_train_class  to 15, and i'm wondering is this a training trick?
And i want to know which conference is this paper accepted?
Hope for your reply, thanks.

**Comment by seongmin-kye** [comment]
Hi.
As described in [Prototypical Networks] paper, it is proved that higher-way in training can improve performance in test.
Also, it is not accepted in conference yet.
Thanks.
