### ISSUE TITLE
Why I convert miniImageNet dataset into the same form as yours in link,but trainning result are different

### ISSUE THREAD

**Issue by Dylanbron** [seongmin-kye/MCT_DFMN#9]
Do you have some special operation with img in the pickle file? I convert the miniImageNet dataset into the same form as yours in link,but trainning result are different. Accuray is much lower than yours. Do you have some operation like transform etc. ?

**Comment by seongmin-kye** [comment]
Did you divide the image by 255?

**Comment by Dylanbron** [comment]
I find the problem in the resize stage, and thanks for your reply
